version: "3.8"

services:
  pug-sample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pug-sample
    volumes:
      - ..:/app
      - volume_trick:/app/node_modules
    working_dir: /app
    ports:
      - 3000:3000
    tty: true

volumes:
  volume_trick:
